### ISSUE TITLE
Document all features

### ISSUE THREAD

**Issue by jackmcdade** [jimblue/statamic-addon-mapbox#1]
Hey there! I would love to see some examples of what this addon does in the README or the documentation. It's pretty unclear what exactly you're getting for $25. 😊

I'm sure you'll get more customers if you can take the time to detail it out a bit!

**Comment by jimblue** [comment]
Hi Jack thanks for your message, I really appreciate.
And... you are totally right, I was a bit on a rush 😅 !
But I should have some time this week-end to document all features.
I'll ping you once online. 👋🏼

**Comment by mnlmaier** [comment]
what's the status on this? :) always looking for cool plugins to make my live easier. will have to resort to a google maps implementation, but your addon might be really helpful in the future!

**Comment by roobottom** [comment]
Ditto on this? I'd love to use mapbox but this project is looking a bit abandoned at the moment?

**Comment by jimblue** [comment]
Hi to everyone @here.
Improvements, new features and a well documented doc are coming.
The project is not abandoner at all, I'm working on it on my free time which mean basically everything week-end and I'm pretty close to finish now.
I don't have a precise release date but should be soon enough hopefully.
Thank you for your patience, you should be happy with what's coming 😄

**Comment by roobottom** [comment]
@jimblue Fair enough, I also have spare time projects. But maybe don't charge for it until you've released minimum documentation?

**Comment by jimblue** [comment]
@roobottom not only the doc, the PR is already pretty advance 😉
