### ISSUE TITLE
how i can add a marker on map?

### ISSUE THREAD

**Issue by web-zz-splanet** [jimblue/statamic-addon-mapbox#2]
how i can add a marker on map?
No documentation...
Please help)

**Comment by mikemartin** [comment]
@jimblue I'd love to use your addon but I'm puzzled on how to add markers too.

**Comment by jimblue** [comment]
Hello,
This feature is not implemented yet, it’s a work in progress.
Should be release beginning of next year 😄

**Comment by mikemartin** [comment]
Thanks @jimblue 
I've been using the [Places fieldtype](https://github.com/spatie/statamic-algolia-places) to search marker locations but it sounds like Algolia is sunsetting their Places API in the new year.

**Comment by jimblue** [comment]
I just release a major refactor of Mapbox with many new features including markers.
Have fun !
